name: minimalist_components
description: Collection of minimalistic components for assorted projects.
version: 1.0.1
homepage: https://github.com/andrelrf1/minimalist_components

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
